-- ============================================================
-- Phase 22A: RoR Trader Production Schema
-- Run this in the Supabase SQL Editor after creating your project.
-- ============================================================

-- ============================================================
-- 1. CORE ENTITY TABLES
-- ============================================================

-- Strategies: the central entity — one row per saved strategy
CREATE TABLE strategies (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    symbol TEXT NOT NULL,
    direction TEXT NOT NULL DEFAULT 'LONG',
    timeframe TEXT NOT NULL DEFAULT '1Min',
    strategy_origin TEXT NOT NULL DEFAULT 'standard',
    forward_testing BOOLEAN DEFAULT true,
    forward_test_start TIMESTAMPTZ,
    alert_tracking_enabled BOOLEAN DEFAULT false,
    alert_tracking_reset_at TIMESTAMPTZ,
    -- config JSONB holds all trigger/confluence/risk/lookback params
    -- (see Strategy Config JSONB Schema in Implementation_Spec_Phase_22.md)
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Backtest results (large blobs)
    kpis JSONB,
    stored_trades JSONB,
    equity_curve_data JSONB,
    -- Forward test / alert tracking results
    live_executions JSONB DEFAULT '[]'::jsonb,
    discrepancies JSONB DEFAULT '[]'::jsonb,
    discrepancies_dismissed_at TIMESTAMPTZ,
    data_refreshed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_strategies_user ON strategies(user_id);
CREATE INDEX idx_strategies_user_symbol ON strategies(user_id, symbol);

-- Portfolios: groups of strategies with allocation and account tracking
CREATE TABLE portfolios (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    name TEXT NOT NULL,
    starting_balance NUMERIC DEFAULT 10000,
    compound_rate NUMERIC DEFAULT 1.0,
    requirement_set_id INTEGER,
    -- strategies is [{strategy_id, risk_per_trade}, ...]
    strategies JSONB DEFAULT '[]'::jsonb,
    cached_kpis JSONB,
    equity_curve_data JSONB,
    -- account tracking: {starting_balance, ledger: [...], notes, notes_updated_at}
    account JSONB,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_portfolios_user ON portfolios(user_id);

-- Requirement Sets: prop firm rules and custom rule sets
-- user_id IS NULL = built-in (shared across all users, read-only)
CREATE TABLE requirement_sets (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    built_in BOOLEAN DEFAULT false,
    firm_key TEXT,
    rules JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_requirements_user ON requirement_sets(user_id);

-- ============================================================
-- 2. ALERT SYSTEM TABLES
-- ============================================================

-- Alerts: signal records generated by Ralph engine or legacy monitor
CREATE TABLE alerts (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    -- Queryable fields for filtering/display
    type TEXT NOT NULL,                 -- 'entry_signal' or 'exit_signal'
    strategy_id INTEGER NOT NULL,
    strategy_name TEXT NOT NULL,
    symbol TEXT NOT NULL,
    direction TEXT NOT NULL,
    timeframe TEXT NOT NULL,
    source TEXT DEFAULT 'ralph',        -- 'ralph' or 'monitor'
    acknowledged BOOLEAN DEFAULT false,
    webhook_sent BOOLEAN DEFAULT false,
    -- Full alert payload (trigger, prices, portfolio context, webhook deliveries, etc.)
    data JSONB NOT NULL DEFAULT '{}'::jsonb,
    timestamp TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_alerts_user ON alerts(user_id);
CREATE INDEX idx_alerts_strategy ON alerts(user_id, strategy_id);
CREATE INDEX idx_alerts_timestamp ON alerts(user_id, timestamp DESC);

-- Alert Configuration: per-user global/strategy/portfolio alert settings
-- Stores the full alert_config.json structure as a single JSONB document
CREATE TABLE alert_config (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    config JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Webhook Templates: reusable payload templates for webhook delivery
-- user_id IS NULL = built-in defaults (shared, read-only)
CREATE TABLE webhook_templates (
    id TEXT PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    category TEXT,
    is_default BOOLEAN DEFAULT false,
    payload_template TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_webhook_templates_user ON webhook_templates(user_id);

-- Inbound Webhook Signals: external signals received via webhook endpoint
CREATE TABLE inbound_signals (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    strategy_id INTEGER,
    payload JSONB NOT NULL,
    processed BOOLEAN DEFAULT false,
    received_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_inbound_signals_user ON inbound_signals(user_id, processed);

-- ============================================================
-- 3. ENGINE & MONITOR TABLES
-- ============================================================

-- Monitor Status: Ralph engine control and status (one row per user)
-- Web UI writes desired_state; worker reads it and starts/stops Ralph
-- Worker writes actual status back to the status JSONB column
CREATE TABLE monitor_status (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    desired_state TEXT DEFAULT 'stopped',   -- 'running' or 'stopped'
    -- Full engine status blob: {running, connected, symbols, strategies, tick_count, ...}
    status JSONB NOT NULL DEFAULT '{}'::jsonb,
    -- Position state blob: {positions: {strategy_id: {status, entry_price, ...}}}
    engine_state JSONB NOT NULL DEFAULT '{}'::jsonb,
    last_heartbeat TIMESTAMPTZ,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Engine Audit Log: fidelity audit trail from Ralph engine
-- Append-only log of bar closes with indicator/trigger/position snapshots
CREATE TABLE engine_audit_log (
    id BIGSERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
    ts TIMESTAMPTZ NOT NULL,            -- bar close timestamp
    symbol TEXT NOT NULL,
    timeframe INTEGER NOT NULL,         -- seconds (60, 300, 900, etc.)
    bar_close NUMERIC NOT NULL,
    indicators JSONB,
    triggers JSONB,
    interpreters JSONB,
    positions JSONB,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX idx_audit_user_ts ON engine_audit_log(user_id, ts DESC);
CREATE INDEX idx_audit_user_symbol ON engine_audit_log(user_id, symbol, ts DESC);

-- ============================================================
-- 4. USER CONFIG TABLES (one row per user, JSONB document)
-- ============================================================

-- User Settings: app preferences (chart_visible_candles, data_feed, timezone, etc.)
CREATE TABLE user_settings (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Confluence Groups: indicator group configurations
CREATE TABLE confluence_groups (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    groups JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- General Packs: time-of-day, session, day-of-week, calendar filters
CREATE TABLE general_packs (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    packs JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- Risk Management Packs: stop-loss and take-profit configurations
CREATE TABLE risk_management_packs (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
    packs JSONB NOT NULL DEFAULT '[]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 5. PUBLIC / WAITLIST TABLE
-- ============================================================

-- Pre-registration waitlist (no auth required for insert)
CREATE TABLE waitlist (
    id SERIAL PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    name TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

-- ============================================================
-- 6. ROW LEVEL SECURITY POLICIES
-- ============================================================

-- Strategy: users see only their own
ALTER TABLE strategies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "strategies_select" ON strategies FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "strategies_insert" ON strategies FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "strategies_update" ON strategies FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "strategies_delete" ON strategies FOR DELETE USING (auth.uid() = user_id);

-- Portfolios: users see only their own
ALTER TABLE portfolios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "portfolios_select" ON portfolios FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "portfolios_insert" ON portfolios FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "portfolios_update" ON portfolios FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "portfolios_delete" ON portfolios FOR DELETE USING (auth.uid() = user_id);

-- Requirement Sets: users see own + built-in (user_id IS NULL), modify only own
ALTER TABLE requirement_sets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "requirements_select" ON requirement_sets FOR SELECT
    USING (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "requirements_insert" ON requirement_sets FOR INSERT
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "requirements_update" ON requirement_sets FOR UPDATE
    USING (auth.uid() = user_id);
CREATE POLICY "requirements_delete" ON requirement_sets FOR DELETE
    USING (auth.uid() = user_id);

-- Alerts: users see only their own
ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "alerts_select" ON alerts FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "alerts_insert" ON alerts FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "alerts_update" ON alerts FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "alerts_delete" ON alerts FOR DELETE USING (auth.uid() = user_id);

-- Alert Config: users see only their own
ALTER TABLE alert_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "alert_config_select" ON alert_config FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "alert_config_insert" ON alert_config FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "alert_config_update" ON alert_config FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "alert_config_delete" ON alert_config FOR DELETE USING (auth.uid() = user_id);

-- Webhook Templates: users see own + defaults (user_id IS NULL), modify only own
ALTER TABLE webhook_templates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "webhook_templates_select" ON webhook_templates FOR SELECT
    USING (auth.uid() = user_id OR user_id IS NULL);
CREATE POLICY "webhook_templates_insert" ON webhook_templates FOR INSERT
    WITH CHECK (auth.uid() = user_id);
CREATE POLICY "webhook_templates_update" ON webhook_templates FOR UPDATE
    USING (auth.uid() = user_id);
CREATE POLICY "webhook_templates_delete" ON webhook_templates FOR DELETE
    USING (auth.uid() = user_id);

-- Inbound Signals: users see only their own
ALTER TABLE inbound_signals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "inbound_signals_select" ON inbound_signals FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "inbound_signals_insert" ON inbound_signals FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "inbound_signals_update" ON inbound_signals FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "inbound_signals_delete" ON inbound_signals FOR DELETE USING (auth.uid() = user_id);

-- Monitor Status: users see only their own
ALTER TABLE monitor_status ENABLE ROW LEVEL SECURITY;
CREATE POLICY "monitor_status_select" ON monitor_status FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "monitor_status_insert" ON monitor_status FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "monitor_status_update" ON monitor_status FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "monitor_status_delete" ON monitor_status FOR DELETE USING (auth.uid() = user_id);

-- Engine Audit Log: users see only their own
ALTER TABLE engine_audit_log ENABLE ROW LEVEL SECURITY;
CREATE POLICY "audit_log_select" ON engine_audit_log FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "audit_log_insert" ON engine_audit_log FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "audit_log_delete" ON engine_audit_log FOR DELETE USING (auth.uid() = user_id);

-- User Settings: users see only their own
ALTER TABLE user_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "settings_select" ON user_settings FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "settings_insert" ON user_settings FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "settings_update" ON user_settings FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "settings_delete" ON user_settings FOR DELETE USING (auth.uid() = user_id);

-- Confluence Groups: users see only their own
ALTER TABLE confluence_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "confluence_groups_select" ON confluence_groups FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "confluence_groups_insert" ON confluence_groups FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "confluence_groups_update" ON confluence_groups FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "confluence_groups_delete" ON confluence_groups FOR DELETE USING (auth.uid() = user_id);

-- General Packs: users see only their own
ALTER TABLE general_packs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "general_packs_select" ON general_packs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "general_packs_insert" ON general_packs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "general_packs_update" ON general_packs FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "general_packs_delete" ON general_packs FOR DELETE USING (auth.uid() = user_id);

-- Risk Management Packs: users see only their own
ALTER TABLE risk_management_packs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "rm_packs_select" ON risk_management_packs FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "rm_packs_insert" ON risk_management_packs FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "rm_packs_update" ON risk_management_packs FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "rm_packs_delete" ON risk_management_packs FOR DELETE USING (auth.uid() = user_id);

-- Waitlist: public insert only, no read/update/delete via API
ALTER TABLE waitlist ENABLE ROW LEVEL SECURITY;
CREATE POLICY "waitlist_insert" ON waitlist FOR INSERT WITH CHECK (true);
GRANT INSERT ON waitlist TO anon;
GRANT USAGE ON SEQUENCE waitlist_id_seq TO anon;

-- ============================================================
-- 7. SEED DATA (built-in records with user_id IS NULL)
-- ============================================================
-- Built-in requirement sets are seeded by the migration script
-- (src/migrate_json_to_db.py) which reads the current requirements.json
-- and inserts records with user_id IS NULL and built_in = true.
--
-- Built-in webhook templates are similarly seeded from webhook_templates.json.
-- This ensures the exact rule values stay in sync with the codebase.
